apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-pvc
  namespace: maven
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
