apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calendar-pvc
  namespace: calendar
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100M
