apiVersion: apps/v1
kind: Deployment
metadata:
  name: anubis
  namespace: invidious
spec:
  selector:
    matchLabels:
      app: anubis
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: anubis
    spec:
      nodeSelector:
        ingress: "true"
      containers:
      - name: anubis
        image: git.gammaspectra.live/git/go-away:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: GOAWAY_CLIENT_IP_HEADER
          value: X-Forwarded-For
        - name: GOAWAY_BACKEND
          value: "iv.duti.dev=http://caddy:80"
        volumeMounts:
        - name: bot-policies
          mountPath: /policy.yml
          subPath: policy.yml
      volumes:
      - name: bot-policies
        configMap:
          name: anubis-bot-policies
---
apiVersion: v1
kind: Service
metadata:
  name: anubis
  namespace: invidious
spec:
  type: ClusterIP
  selector:
    app: anubis
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: anubis-bot-policies
  namespace: invidious
data:
  policy.yml: |
    challenges:
      js-pow-sha256:
        runtime: js
        duration: 24h
        parameters:
          path: "js-pow-sha256"
          js-loader: load.mjs
          wasm-runtime: runtime.wasm
          wasm-runtime-settings:
            difficulty: 10
          verify-probability: 0.02
    rules:
      - name: allow companion
        conditions:
          - 'path.startsWith("/companion/")'
        action: pass
      - name: block-non-browsers
        conditions:
          - '!userAgent.matches("Mozilla/")'
        action: deny
      - name: verify-everything
        conditions:
          - 'path.startsWith("/")'
        action: challenge
        settings:
          challenges: ["js-pow-sha256"]
