apiVersion: apps/v1
kind: Deployment
metadata:
  name: anubis
  namespace: invidious
spec:
  selector:
    matchLabels:
      app: anubis
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: anubis
    spec:
      nodeSelector:
        capability.duti.dev/performance: high
        kubernetes.io/arch: amd64
      containers:
      - name: anubis
        image: ghcr.io/acheong08/go-away:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: GOAWAY_CLIENT_IP_HEADER
          value: X-Forwarded-For
        - name: GOAWAY_BACKEND
          value: "*.duti.dev=http://caddy:80"
        volumeMounts:
        - name: bot-policies
          mountPath: /policy.yml
          subPath: policy.yml
      volumes:
      - name: bot-policies
        configMap:
          name: anubis-bot-policies
---
apiVersion: v1
kind: Service
metadata:
  name: anubis
  namespace: invidious
spec:
  type: ClusterIP
  selector:
    app: anubis
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: anubis-bot-policies
  namespace: invidious
data:
  policy.yml: |
    challenges:
      js-pow-sha256:
        runtime: js
        duration: 24h
        parameters:
          path: "js-pow-sha256"
          js-loader: load.mjs
          wasm-runtime: runtime.wasm
          wasm-runtime-settings:
            difficulty: 15
          verify-probability: 0.02
    rules:
      - name: block-non-browsers
        conditions:
          - 'userAgent == "Mozilla/5.0 (X11; Linux x86_64; rv:150.0) Gecko/20100101 Firefox/150.0"'
          - 'userAgent == "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:147.0) Gecko/20100101 Firefox/147.0"'
          - 'userAgent == "Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko)"'
          - '"Cookie" in headers && headers["Cookie"].contains("ImAHuman=true")'
        action: pass
      - name: allow-webhook
        conditions:
          - 'path == "/feed/webhook/v1"'
          - 'path == "/supersecretlink"'
        action: pass
      - name: block-everyone
        conditions:
          - 'path.startsWith("/")'
        action: block
