apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    spec.ingressClassName: traefik
  labels:
    app: monitor
  name: monitor-ingress
  namespace: monitoring
spec:
  rules:
  - host: kube-monitor.duti.dev
    http:
      paths:
      - backend:
          service:
            name: caddy
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - kube-monitor.duti.dev
    secretName: monitor-tls
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: monitoring
data:
  Caddyfile: |
    :80 {
        route {
            basic_auth {
                kube $2a$14$hovE7N8ydaVvrHFe6A4APOQeaRME30KvkYjjXEU7VP3.MAgHrUp8K
            }
            reverse_proxy kube-prometheus-stack-grafana:80 {
                #header_up authorization "Bearer {env.BEARER_TOKEN}"
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy
        image: caddy:latest
        ports:
        - containerPort: 80
        #env:
        #- name: BEARER_TOKEN
        #  valueFrom:
        #    secretKeyRef:
        #      name: admin-user
        #      key: token
        volumeMounts:
        - name: caddy-config-volume
          mountPath: /etc/caddy
      volumes:
      - name: caddy-config-volume
        configMap:
          name: caddy-config
          items:
          - key: Caddyfile
            path: Caddyfile
---
apiVersion: v1
kind: Service
metadata:
  name: caddy
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: caddy
  ports:
    - port: 80
      targetPort: 80
