apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webdav-pvc
  namespace: webdav
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100M
