apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: statichost-pvc
  namespace: statichost
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50M
