apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: bouncer
    namespace: kube-system
spec:
    plugin:
        bouncer:
            Enabled: "true"
            crowdsecMode: live
            crowdsecLapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
            # LogLevel: DEBUG
            crowdsecLapiScheme: http
            crowdsecLapiKey: 
              secret:
                name: crowdsec-bouncer
                key: api-key
