apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: bouncer
    namespace: kube-system
spec:
    plugin:
        bouncer:
            Enabled: "true"
            crowdsecMode: stream
            crowdsecLapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
            crowdsecLapiScheme: http
            crowdsecLapiKey: "REDACTED"
