container_runtime: containerd
agent:
  # To specify each pod you want to process it logs (pods present in the node)
  acquisition:
    # The namespace where the pod is located
    - namespace: kube-system
      # The pod name
      podName: traefik-*
      # as in crowdsec configuration, we need to specify the program name so the parser will match and parse logs
      program: traefik
  # Those are ENV variables
  env:
    - name: PARSERS
      value: "crowdsecurity/cri-logs"
    - name: COLLECTIONS
      value: "crowdsecurity/traefik"
  persistentVolume:
    config:
      enabled: false
lapi:
  replicas: 1
  dashboard:
    enabled: false
    ingress:
      enabled: false
  persistentVolume:
    config:
      enabled: true
    data:
      enabled: true
  extraVolumes:
    - name: aws-api-blocklist
      configMap:
        name: aws-api-blocklist
  extraVolumeMounts:
    - name: aws-api-blocklist
      mountPath: /etc/crowdsec/aws_api_blocklist
  env:
    - name: ENROLL_KEY
      valueFrom:
        secretKeyRef:
          name: crowdsec-enroll
          key: enroll_key
    - name: ENROLL_INSTANCE_NAME
      value: "k3s_cluster"
    - name: ENROLL_TAGS
      value: "k3s"
  nodeSelector:
    residential: "true"
