apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: bouncer
    namespace: kube-system
spec:
    plugin:
        bouncer:
            Enabled: "true"
            crowdsecMode: live
            crowdsecLapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
            # LogLevel: DEBUG
            crowdsecLapiScheme: http
            crowdsecLapiKey: "bxhnzd+LAlFiEAirEuEPdhsDG6oao1wSqedNENp4/nw"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: crowdsec
  name: crowdsec-ingress
  namespace: crowdsec
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    spec.ingressClassName: traefik
spec:
  rules:
  - host: kube-crowdsec.duti.dev
    http:
      paths:
      - backend:
          service:
            name: crowdsec-service
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - kube-crowdsec.duti.dev
    secretName: crowdsec-tls
