apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 2.58.53.183/32
  - 192.168.122.165/32

---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: advertise
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
