experimental:
  plugins:
    bouncer:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.3.0"
additionalArguments:
  - "--entrypoints.web.http.middlewares=kube-system-bouncer@kubernetescrd"
  - "--entrypoints.websecure.http.middlewares=kube-system-bouncer@kubernetescrd"
  - "--providers.kubernetescrd"
deployment:
  kind: DaemonSet
  ports:
  web:
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      insecure: true
  websecure:
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      insecure: true
  hostNetwork: true
service:
  spec:
    externalTrafficPolicy: Local
